name: animate-sdl2-example
version: '0.0.0'
category: Game
synopsis: Animation for sprites
description: Prototypical sprite animation with type-safety.
maintainer: Joe Vargas
extra-source-files:
- package.yaml
- README.md
- stack.yaml
- dino.yaml
- dino.png
data-files:
- dino.yaml
- dino.png
ghc-options: -Wall
default-extensions:
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- NamedFieldPuns
- ScopedTypeVariables
- OverloadedStrings
executables:
  animate-sdl2-example:
    dependencies:
    - base >=4.7 && <5
    - animate
    - animate-sdl2
    - sdl2
    - containers
    - text
    - aeson
    - StateVar
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: .
github: jxv/animate-sdl2
license: BSD3
